config/routes.rb
Rails.application.routes.draw do

  root to: 'users#profile'
  resources :users, except: [:index, :show, :destroy] do
    member do
      get 'reset_password'
    end
  end

  get '/users', to: 'administrators#index_user'
  get '/users/:id', to: 'administrators#show_user'
  delete '/users/:id', to: 'administrators#destroy_user'
  get '/users/:id/index_task', to: 'tasks#index_task', as: 'index_task_user'
  get '/users/:user_id/tasks/:id/accept_task', to: 'tasks#accept_task', as: 'accept_task_user'

  get 'user/profile', to: 'users#profile'
  namespace :administrators do
    get 'new_user'
    post 'create_user'
    get 'edit_user'
    patch 'update_user'
    put 'update_user'
    get 'index_project'
    get 'index_task'
  end

  resources :projects do
    member  do
      get 'invite_participant'
    end
    resources :tasks do
      member  do
        get 'assign_task'
      end
      member do
        get 'new_subtask'
      end
      member do
        post 'create_subtask'
      end
      resources :hours
      resources :comments, except:[:show]
    end
  end
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get     '/report', to: 'reports#generate'
  post     '/report', to: 'reports#search'
end

app/models/task.rb
class Task < ActiveRecord::Base
  require 'csv'
  has_many :sub_tasks,  class_name: "Task", foreign_key: "parent_task_id"
  has_many :comments, dependent: :delete_all
  has_many :hours, dependent: :delete_all
  belongs_to :project
  belongs_to :parent_task, class_name: "Task"
  belongs_to :user
  has_and_belongs_to_many :assignees, class_name: "User",  join_table: "assigned_tasks_assignees"
  belongs_to :task_type

  validates :title, :description, :status, :task_type, :presence => true
  scope :created_between, lambda{ |start_time, end_time| where ('created_at BETWEEN ? And ?'), start_time, end_time }
  scope :task_status, lambda{ |status| where(:status => status)}
  scope :task_type, lambda{ |type_id| where(:task_type_id => type_id)}
  scope :validated_tasks, ->{where(deleted: false)}

  def self.to_csv
    attributes = %w{id title type status total_work_time}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |task|
        csv << [task.id, task.title, task.task_type.name, task.status, task.task_total_work_time]
      end
    end
  end

  def without_subtask_work_time
    hours.validated_hours.map{|t| t.work_time}.sum
  end

  def task_total_work_time
    without_subtask_work_time + sub_tasks.map{|s| s.task_total_work_time}.sum
  end

  def update_assignment_status
    if assignees.count == 0
      update(assignment_status: "To Be Assigned", assignment_confirmed_user_id: nil)
    elsif assignees.count == 1
      update(assignment_status: "Confirmed", assignment_confirmed_user_id: assignees.first.id)
    elsif assignees.count > 1
      if assignment_confirmed_user_id == nil || assignees.map(&:id).exclude?(assignment_confirmed_user_id)
        update(assignment_status: "Pending", assignment_confirmed_user_id: nil)
      end
    end
  end

  def update_task_type(type)
    # parameter type is the string of task type id
    if type != task_type_id.to_s
      # when the type of a task is changed, task will delete this type and add a new type
      self.task_type.tasks.delete(self)
      self.task_type = TaskType.find_by(id: type)
    end
  end

  def update_assignee(assignees_id)
    # parameter participants indicate an array of participants ids string
    if assignees_id.blank?
      assignees.delete(assignees.all)
    else
      assignees.all.each do |assignee|
        if assignees_id.exclude?(assignee.id.to_s)
          assignees.delete(assignee)
        end
      end
      #add new participant to project
      assignees_id.each do |id|
        if !assignees.exists?(id: id)
          user = User.find_by(id: id)
          assignees << user
        end
      end
    end
    # update task assignment status
    update_assignment_status
  end

  def set_subtasks_comments_hours_to_deleted
    comments.update_all(deleted: true)
    hours.update_all(deleted: true)
    self.sub_tasks.each do |sub_task|
      sub_task.update(deleted: true)
      sub_task.set_subtasks_comments_hours_to_deleted
    end
  end

end

app/models/task_type.rb
class TaskType < ActiveRecord::Base
  has_many :tasks
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :load_task_before_action, only: [:show, :edit, :update, :destroy, :assign_task]
  before_action :is_the_correct_user_before_action, only: [:accept_task]

  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end

  def new_subtask
    @project = Project.find(params[:project_id])
    @parent_task = Task.find(params[:id])
    @task = @parent_task.sub_tasks.new
    @task.project_id = @project.id
  end

  def create
    @project = Project.find(params[:project_id])
    @task = Task.new(task_params)
    @task.project_id = @project.id
    @task.user_id = current_user.id
    @task.task_type_id = params[:task][:task_type]
    if @task.save
      @task.update_assignee(params[:task][:assignees_id])
      redirect_to  project_task_path(@task.project, @task)
    else
      render 'new'
    end
  end

  def create_subtask
    @project = Project.find(params[:project_id])
    @parent_task = Task.find(params[:id])
    @task = Task.new(task_params)
    @task.project_id = @project.id
    @task.parent_task_id = @parent_task.id
    @task.user_id = current_user.id
    @task.task_type_id = params[:task][:task_type]
    if @task.save
      @task.update_assignee(params[:task][:assignees_id])
      redirect_to project_task_path(@task.project, @task)
    else
      render 'new_subtask'
    end
  end

  def show
    @hour = Hour.new
    @hour.task_id = @task.id
    @comment = Comment.new
    @comment.task_id = @task.id
  end

  def edit
    @project = Project.find(params[:project_id])
  end

  def update
    @project = Project.find(params[:project_id])
    @task.update_task_type(params[:task][:task_type])
    if @task.update(task_params)
      @task.update_assignee(params[:task][:assignees_id])
      redirect_to project_task_path(@task.project_id, @task.id)
    else
      render 'edit'
    end
  end

  def destroy
    @project =  Project.find(params[:project_id])
    set_record_to_deleted(@task)
    @task.set_subtasks_comments_hours_to_deleted
    redirect_to @project
  end

  def assign_task
    if params.has_key?("commit")
      if params.has_key?("task")
        # after submitting the form, assign task if choose any users
        @task.update_assignee(params[:task][:assignees_id])
      else
        # remove previous assignees if didn't choose any users
        @task.update_assignee([])
      end
      return redirect_to project_task_path(@task.project, @task)
    end
  end

  def index_task
    # return the tasks by its relevant: confirmed > pending > create > others
    @tasks = current_user.return_tasks_by_relevant
    if params[:task_filter_selected] == "all_tasks"
      @tasks = current_user.return_tasks_by_relevant
    elsif params[:task_filter_selected] == "confirmed_tasks"
      @tasks = current_user.assigned_and_confirmed_tasks
    elsif params[:task_filter_selected] == "create_tasks"
      @tasks = current_user.create_tasks_and_can_access
    elsif params[:task_filter_selected] == "pending_tasks"
      @tasks = current_user.assigned_and_pending_tasks
    elsif params[:task_filter_selected] == "other_accessed_tasks"
      @tasks = current_user.have_accessed_tasks
    elsif params[:task_filter_selected] == "feature"
      @tasks = current_user.return_taks_of_type(current_user.return_tasks_by_relevant, "Feature")
    elsif params[:task_filter_selected] == "bug"
      @tasks = current_user.return_taks_of_type(current_user.return_tasks_by_relevant, "Bug")
    elsif params[:task_filter_selected] == "improvement"
      @tasks = current_user.return_taks_of_type(current_user.return_tasks_by_relevant, "Improvement")

    elsif params.has_key?("task_filter_selected") && params[:task_filter_selected].blank?
      flash.notice = "please choose a scope"
      return redirect_to index_task_user_path(current_user)
    end
  end

  def accept_task
    @task = Task.find_by(id: params[:id])
    @user = User.find_by(id: params[:user_id])
    if params.has_key?("commit")
      if params[:accept]
        @task.update(assignment_confirmed_user_id: params[:user_id])
        @task.update(assignment_status: "Confirmed")
      else
        @task.update(assignment_confirmed_user_id: nil)
        @task.update(assignment_status: "Pending")
      end
      return redirect_to   project_task_path(@task.project, @task)
    end
    if params.has_key?("accept")
      @task.update(assignment_confirmed_user_id: params[:user_id])
      @task.update(assignment_status: "Confirmed")
      return redirect_to  project_task_path(@task.project, @task)
    end
  end


  private
  def load_task_before_action
    @task = Task.find_by(id: params[:id])
    if @task.blank? || @task.deleted
      flash.notice = "Task doesn't exist !"
      return redirect_to root_path
    end
    # only allow participants and administrator access a task under a project
    if !current_user.has_role?("administrator") && !@task.project.participants.exists?(current_user)
      flash.notice = "You don't have privilege !"
      return redirect_to root_path
    end
  end

  def is_the_correct_user_before_action
    if current_user.id.to_s != params[:user_id] || Task.find_by(id: params[:id]).assignees.exclude?(current_user)
      flash.notice = "You don't have privilege !"
      return redirect_to root_path
    end
  end

  def task_params
    params.require(:task).permit(:title, :description, :status, :assignees_id)
  end


end

app/helpers/tasks_helper.rb
module TasksHelper

  def task_status(task)
    case task.status
      when "open"
        "Open"
      when "in_progress"
        "In Progress"
      when "waiting"
        "Waiting"
      when "resolved"
        "Resolved"
    end
  end



end

app/views/tasks/_comment.html.erb
<div class="comment_show">
  <h6 class="comment_show_author">Comment by <%= comment.user.user_name %></h6>
  <p class = "comment_show_time">Posted <%= distance_of_time_in_words(comment.task.created_at, comment.created_at) %> later</p>
  <li class = "comment_show_modify">
    <%# only admin can edit or delete a comment %>
    <% if current_user.has_role?("administrator") %>
        <%= link_to "edit", edit_project_task_comment_path(comment.task.project, comment.task_id, comment.id), {:style=>'color:red'} %>
        | <%= link_to "delete",  project_task_comment_path(comment.task.project, comment.task_id, comment.id), :style=>'color:red',
                      method: :delete, data: { confirm: "You sure?" }%>
    <% end %>
  </li>
  <%# add warning icon to edited comment %>
  <% if comment.edit %>
      <%= image_tag("comment_edit.png", height: '28', width: '28', class: "comment_show_icon") %>
  <% end %>
  <p class="comment"><%= comment.body %></p>
</div>

app/views/tasks/_form.html.erb
<%= form_for [@project,@task] do |f| %>
    <%= render partial: 'users/error_messages', object: @task, as: :item %>
    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </p>
    <br/>
    <p>
      <%= f.label :description %><br/>
      <%= f.text_area :description %>
    </p>
    <br/>
    <p>
      <%= f.label :status %><br/>
      <%= f.select :status, options_for_select([["Open", "open"], ["In Progress", "in_progress"], ["Waiting", "waiting"], ["Resloved", "resloved"]], :selected => @task.status)%>
    </p>
    <br/>
    <p>
      <% if local_assigns[:edit] %>
          <%= f.label :task_type %><br/>
          <%= f.collection_select :task_type, TaskType.all, :id, :name,:selected => @task.task_type.id %>
      <% else %>
          <%= f.label :task_type %><br/>
          <%= f.collection_select :task_type, TaskType.all, :id, :name, prompt: "Please choose a type"%>
      <% end %>
    </p>
    <br/>
    <p>
      <%= f.label :Assign_This_Task %></br>
      <%= f.collection_check_boxes :assignees_id, @project.participants, :id, :user_name, :checked => @task.assignees.map(&:id), :include_hidden => false %>
    </p>
    <br/>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/tasks/_hour.html.erb
<div class="time_detail">
  <% if @task.task_total_work_time != 0 %>
      <ul class="time_detail_work_time">
        <% @task.hours.each do |h| %>
            <li class="time_detail_user_work_time"><%= link_to h.work_time, [h.task.project, h.task, h],
                                                               class: "time_detail_user_time_link" %> h | <%= h.user.user_name %></li>
        <% end %>
        <% @task.sub_tasks.each do |t| %>
            <% if t.task_total_work_time > 0 %>
                <li class="time_detail_subtask_work_time"><%= link_to t.task_total_work_time, [t.project, t],
                                                                      class: "time_detail_task_link" %> h | <%= t.title %></li>
            <% end %>
        <% end %>
      </ul>
      <br/>
  <% end %>

</div>

app/views/tasks/accept_task.html.haml
%h1 Accept a Task
%p
  Task Title :
  = @task.title
%br
%p
  Task Author :
  = @task.user.user_name
%br
%p
  Task Description :
  = @task.description
%br
%ul{:class => "accept_task_assignee_name"}
  Task Assignees :
  - @task.assignees.each do |assignee|
    %li
      = assignee.user_name
      - if assignee != @task.assignees.last
        |
%br
= form_tag  accept_task_user_path(@user, @task), method: :get
%p
  Take the task
  = check_box_tag :accept, true
%p
  = submit_tag "OK"

app/views/tasks/assign_task.html.erb
<div class="assign_task">
  <h1>Assign Task</h1>
  <%= form_for @task, url:assign_task_project_task_path(@task.project, @task) , method: :get  do |f| %>
      <p>
        <%= f.label :Assign_This_Task_To %></br>
        <%= f.collection_check_boxes :assignees_id, @task.project.participants, :id, :user_name, :checked => @task.assignees.map(&:id), :include_hidden => false %>
      </p>
      <p><%= f.submit "Ok"%></p>
  <% end %>
  <br/>
  <h3><%= link_to "<< invite more participant", invite_participant_project_path(@task.project)%></h3>
</div>

app/views/tasks/edit.html.erb
<div class="edit_task">
  <h1>Edit a Task</h1>
  <%= render partial: "form", locals: {edit: true} %>
</div>

app/views/tasks/index_task.html.haml
%h1 Tasks
.user_task_filter
  = form_tag index_task_user_path, :method => :get
  .user_task_filter_select
    Task Filter
    = select_tag :task_filter_selected, options_for_select([["All Tasks", "all_tasks"],["Create Tasks", "create_tasks"], ["Confirmed Tasks", "confirmed_tasks"],["Pending Tasks", "pending_tasks"], ["Other Accessed Tasks", "other_accessed_tasks"], ["Feature", "feature"], ["Bug", "bug"], ["Improvement", "improvement"]]), prompt: "Please choose"
  .user_task_filter_submit
    = submit_tag 'submit'
.user_tasks_wrap
  %h2
    Tasks (#{@tasks.size})
  - if @tasks.present?
    %ul{:id => "user_tasks"}
      - @tasks.each do |task|
        %li
          = link_to task.title,  project_task_path(task.project, task), class: 'user_tasks_wrap_task_title'
          - if task.assignees.exists?(current_user) && task.assignment_confirmed_user_id == nil
            %p{:class => "user_tasks_wrap_task_pending"}
              |
              = link_to image_tag("task_pending.jpg", height: '40', width: '80', class: "task_pending_icon"), accept_task_user_path(current_user, task)
              |
              = link_to image_tag("take_task.jpg", height: '40', width: '40'), accept_task_user_path(current_user, task, accept: true), data: {confirm: "Are you sure to take the task"}
          - if task.assignment_confirmed_user_id == current_user.id
            %p{:class => "user_tasks_wrap_task_confirmed"}
              |
              = image_tag("task_confirmed.jpg", height: '50', width: '80', class: "task_confirmed_icon")
        %br
%br
%br
%h3
  = link_to "<< Back to Personal Profile", root_path

app/views/tasks/new.html.erb
<div class="new_task">
  <h1>Create a New Task</h1>
  <%= render partial: "form" %>
</div>

app/views/tasks/new_subtask.html.erb
<div class="new_subtask">
  <h1>Create a Sub Task</h1>
  <%= form_for @task, url:create_subtask_project_task_path(@task.project, @task.parent_task) do |f| %>
      <%= render partial: 'users/error_messages', object: @task, as: :item %>
      <p>
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </p>
      <br/>
      <p>
        <%= f.label :description %><br/>
        <%= f.text_area :description %>
      </p>
      <br/>
      <p>
        <%= f.label :status %><br/>
        <%= f.select :status, options_for_select([["Open", "open"], ["In Progress", "in_progress"], ["Waiting", "waiting"], ["Resloved", "resloved"]], :selected => @task.status)%>
      </p>
      <br/>
      <p>
        <%= f.label :task_type %><br/>
        <%= f.collection_select :task_type, TaskType.all, :id, :name, prompt: "Please choose a type" %>
      </p>
      <br/>
      <p>
        <%= f.label :Assign_This_Task %></br>
        <%= f.collection_check_boxes :assignees_id, @project.participants, :id, :user_name, :checked => @task.assignees.map(&:id), :include_hidden => false %>
      </p>
      <br/>
      <p>
        <%= f.submit %>
      </p>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class= "task_wrap">
  <h1>Task : <%= @task.title %></h1>
  <p class="task_wrap_author">Author : <%= @task.user.user_name %></p>
  <div class="task_wrap_modify">
    <%= link_to  "assign task", assign_task_project_task_path(@task.project, @task), {:style=>'color:red'}%>
    | <%= link_to  "edit" , edit_project_task_path(@task.project, @task), {:style=>'color:red'}%>
    | <%= link_to  "delete" , project_task_path(@task.project, @task), :style=>'color:red', method: :delete,
                   data: {confirm: "Really delete the task?"}%>
  </div>

  <br/><br/>
  <p>Created at : <%= @task.created_at %></p>
  <br/>
  <p>Task Number : <%= @task.id%></p>
  <br/>
  <p>From Project : <%= link_to @task.project.title,project_path(@task.project)%>
  <br/><br/>
  <% if @task.parent_task.present? %>
      <p>Parent Task : <%= link_to @task.parent_task.title,  project_task_path(@task.project, @task.parent_task) %></p>
  <% else %>
      <p>Parent Task : No Parent Task</p>
  <% end %>
  <br/>
  <p>Description : <%= @task.description%></p>
  <br/>
  <p>Status : <%= task_status(@task) %></p>
  <br/>
  <p>Task Type : <%= @task.task_type.name %></p>
  <br/>
  <% if @task.assignees.blank? %>
      <p>Assignees : No Assignees</p>
  <% else %>
      <ul class="task_wrap_assignee_name"> Assignee :
        <% @task.assignees.each do |assignee| %>
            <li>
              <% if @task.assignment_confirmed_user_id == assignee.id %>
                <%= assignee.user_name %><%= image_tag("task_check.png", height: '30', width: '30', class: "task_check_icon") %>
              <% else %>
                  <%= assignee.user_name %>
              <% end %>
              <% if assignee != @task.assignees.last %>
                  |
              <% end %>
            </li>
        <% end %>
      </ul>
  <% end %>
  <br/>
  <p class="task_wrap_assignment_status">Assignment Status : <%= @task.assignment_status %></p>
  <br/>
  <div class="task_time">
    <div class="task_time_show_time">
      <p>Task Total Time : <%= @task.task_total_work_time %> h</p>
    </div>
    <br/>
    <%= render partial: 'hour' %>
    <%= render partial: 'hours/form' %>
  </div>
  <br/><br/>
</div>
<div class = "subtask_wrap">
  <h2>SubTasks(<%= @task.sub_tasks.size %>)</h2>
  <ul id="subtasks">
    <% @task.sub_tasks.each do |subtask| %>
      <li>
        <%= link_to subtask.title, project_task_path(subtask.project_id, subtask.id)%>
      </li>
    <% end %>
  </ul>
  <br/>
  <%= link_to "create subtask", new_subtask_project_task_path(@task.project, @task),  class: "new" %>
  <br/><br/>
</div>

<div class="comment_wrap">
  <h2>Comments(<%= @task.comments.size %>)</h2>
  <%= render partial: 'tasks/comment', collection: @task.comments.reverse %>
  <h3>Post a Comment</h3>
  <%= render partial: 'comments/form' %>
  <br/>
</div>

<div class="footer">
  <h3>
    <% if @task.parent_task == nil %>
        <%= link_to "<< Back to Project", project_path(@task.project_id) %>
    <% else %>
        <%= link_to "<< Back to Parent Task", project_task_path(@task.project_id, @task.parent_task)%>
    <% end %>
  </h3>
</div>