config/routes.rb
Rails.application.routes.draw do

  root to: 'users#profile'
  resources :users, except: [:index, :show, :destroy] do
    member do
      get 'reset_password'
    end
  end

  get '/users', to: 'administrators#index_user'
  get '/users/:id', to: 'administrators#show_user'
  delete '/users/:id', to: 'administrators#destroy_user'
  get '/users/:id/index_task', to: 'tasks#index_task', as: 'index_task_user'
  get '/users/:user_id/tasks/:id/accept_task', to: 'tasks#accept_task', as: 'accept_task_user'

  get 'user/profile', to: 'users#profile'
  namespace :administrators do
    get 'new_user'
    post 'create_user'
    get 'edit_user'
    patch 'update_user'
    put 'update_user'
    get 'index_project'
    get 'index_task'
  end

  resources :projects do
    member  do
      get 'invite_participant'
    end
    resources :tasks do
      member  do
        get 'assign_task'
      end
      member do
        get 'new_subtask'
      end
      member do
        post 'create_subtask'
      end
      resources :hours
      resources :comments, except:[:show]
    end
  end
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get     '/report', to: 'reports#generate'
  post     '/report', to: 'reports#search'
end

app/models/user.rb
class User < ActiveRecord::Base
  require 'csv'
  has_many :projects
  has_many :hours
  has_many :role_maps
  has_many :roles, through: :role_maps
  has_many :tasks
  has_many :comments
  has_and_belongs_to_many :assigned_projects, class_name: "Project",  join_table: "assigned_projects_participants"
  has_and_belongs_to_many :assigned_tasks, class_name: "Task",  join_table: "assigned_tasks_assignees"

  before_save { self.email = email.downcase }
  before_save {self.user_name = user_name.delete(' ')}
  # before_destroy :release_all_associations
  # before_destroy :release_all_assigned_tasks
  validates :user_name,  presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: false}
  validates :email,  presence: true, length: {maximum: 200}, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "invalid email format"},
      uniqueness: {case_sensitive: false}
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, length: {minimum: 4}, if: :password_validation
  after_initialize :set_password_validation_default_value
  has_secure_password
  attr_accessor :password_validation
  scope :created_between, lambda{ |start_time, end_time| where ('created_at BETWEEN ? And ?'), start_time, end_time }
  scope :user_activated, lambda{ |status| where(:activated => status)}


  def self.to_csv
    attributes = %w{id user_name email first_name last_name status total_work_time}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |user|
        csv << [user.id, user.user_name, user.email, user.first_name, user.last_name, user.status, user.user_total_work_time]
      end
    end
  end

  def has_role?(role_name)
    roles.exists?(role_name: role_name)
  end

  def user_total_work_time
    hours.validated_hours.map{|t| t.work_time}.sum
  end

  def assigned_and_confirmed_tasks
    assigned_tasks.validated_tasks.where(assignment_confirmed_user_id: self.id)
  end

  def assigned_and_pending_tasks
    assigned_tasks.validated_tasks.where(assignment_confirmed_user_id: nil)
  end

  # tasks which are created by the user and the user can also access them
  def create_tasks_and_can_access
    returned_tasks = []
    tasks.validated_tasks.each do |task|
      if task.project.participants.include?(self)
        returned_tasks = returned_tasks + [task]
      end
    end
    return returned_tasks
  end

  # tasks that created by user without being assigned to himself
  def create_tasks_without_being_assigned
    create_tasks_and_can_access - assigned_and_confirmed_tasks - assigned_and_pending_tasks
  end

  def have_accessed_tasks
    returned_tasks = []
    assigned_projects.validated_projects.each do |project|
      returned_tasks = returned_tasks + project.tasks.validated_tasks
    end
    returned_tasks - assigned_and_confirmed_tasks - assigned_and_pending_tasks - tasks.validated_tasks
  end

  # return the tasks by its relevant: confirmed > pending > create > others
  def return_tasks_by_relevant
    assigned_and_confirmed_tasks + assigned_and_pending_tasks + create_tasks_without_being_assigned + have_accessed_tasks
  end

  def return_admin_tasks_by_relevant
    assigned_and_confirmed_tasks + assigned_and_pending_tasks + create_tasks_without_being_assigned + (Task.all.validated_tasks - assigned_and_confirmed_tasks - assigned_and_pending_tasks - create_tasks_without_being_assigned)
  end

  def return_taks_of_type(tasks, type)
    tasks.select{|task| task.task_type_id == TaskType.find_by(name: type).id}
  end

  def create_projects_and_participate
   projects.validated_projects - ( projects.validated_projects - assigned_projects.validate_projects )
  end

  def update_role(roles_id)
    # parameter roles indicate an array of role ids string
    # no roles are chosen
    if roles_id.blank?
      return role_maps.delete(role_maps.all)
    end
    #delete roles of user which are not chosen
    role_maps.all.each do |role_map|
      if roles_id.exclude?(role_map.role_id.to_s)
        role_map.destroy
      end
    end
    #add new choosed role to user
    roles_id.each do |role_id|
      if !role_maps.exists?(role_id: role_id)
        role_maps.create(role_id: role_id)
      end
    end
  end

  def status
    if activated
      "Active"
    else
      "Inactive"
    end
  end

  private
  def set_password_validation_default_value
    self.password_validation = true
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_user_logged_in_before_action, only: [:new, :create]
  before_action :is_the_correct_user_before_action, only: [:reset_password]
  before_action :verify_user_already_logged_in_before_action, only: [:new]
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      # set new user as developer
      @user.role_maps.create(role_id: Role.find_by(role_name: "developer").id)
      flash.notice = "Thanks for signing up"
      return redirect_to login_path
    else
      return render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    # check if user reset password, if doesn't, skip the password validation
    if params[:user][:password].blank?
      @user.password_validation = false
    end
    if @user.update(user_params)
      return redirect_to root_path
    end
    if !params[:user].has_key?("password")
      return render 'edit'
    else
       return render 'reset_password'
    end
  end

  def reset_password
    @user = User.find(params[:id])
  end

  def profile
    @user = User.find(current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :email, :first_name, :last_name, :password, :password_confirmation, :activated)
  end

  def is_the_correct_user_before_action
    # when the current user tries to do something to other users account
    if !(current_user.has_role?("administrator") || current_user == @user = User.find(params[:id]))
      flash.notice = "You don't have the privilege"
      return redirect_to root_path
    end
  end




end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_error_messages.html.erb
<% if item.errors.any? %>
    <div class="error-explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(item.errors.count, "error") %>.
      </div>
      <ul>
        <% item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user  do |f| %>
    <%= render partial: 'error_messages', object: @user, as: :item %>
    <%= f.label :user_name %>
    <%= f.text_field :user_name%>
    <br/><br/>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br/><br/>
    <%= f.label :first_name%>
    <%= f.text_field :first_name %>
    <br/><br/>
    <%= f.label :last_name%>
    <%= f.text_field :last_name %>
    <br/><br/>
    <% if local_assigns[:sign_up] %>
        <%= f.label :password %>
        <%= f.password_field :password, placeholder: "minimum 4 characters" %>
        <br/><br/>
        <%= f.label :password_confirmation%>
        <%= f.password_field :password_confirmation %>
        <br/><br/>
    <% end %>
    <% if local_assigns[:edit] %>
        <%= link_to "Reset Password", reset_password_user_path(@user)%>
        <br/><br/>
    <% end %>
    <%= f.submit%>
<% end %>

app/views/users/edit.html.erb
<h1>Update Your Information</h1>
<%= render partial: "form", object: @user, locals: {sign_up: false, edit: true} %>

app/views/users/index.html.erb
<h1>All Users</h1>
<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.user_name, user, class: 'user_title' %>
      <% unless user.has_role?("administrator") %>
          | <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
          | <%= link_to "modify", edit_user_path(user.id) %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a New User", new_user_path, class: "new" %>
<br/><br/>
<h3><%= link_to "<< Back to Personal Profile", @user %></h3>

app/views/users/index_task.html.haml
%h1 Tasks
.user_task_filter
  = form_tag index_task_user_path, :method => :get
  .user_task_filter_select
    Task Filter
    = select_tag :task_filter_selected, options_for_select([["All Tasks", "all_tasks"],["Create Tasks", "create_tasks"], ["Assigned and Confirmed Tasks", "assigned_and_confirmed_tasks"],["Assigned and Pending Tasks", "assigned_and_pending_tasks"], ["Other Accessed Tasks", "other_accessed_tasks"]]), prompt: "Please choose"
  .user_task_filter_submit
    = submit_tag 'submit'
.user_tasks_wrap
  %h2
    Tasks (#{@tasks.size})
  - if @tasks.present?
    %ul{:id => "user_tasks"}
      - @tasks.each do |task|
        %li
          = link_to task.title,  project_task_path(task.project, task), class: 'task_title'
          - if task.assignees.exists?(current_user)
            11111
          - if task.assignment_confirmed_user_id == current_user.id
            333
%br
%br
%h3
  = link_to "<< Back to Personal Profile", root_path

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render partial: "form", object: @user, locals: {sign_up: true, edit: false} %>

app/views/users/profile.html.haml
%h1 Welcome to GroupIt
%p
  User Name :
  = @user.user_name
%br
%p
  Email Address :
  = @user.email
%br
%p
  First Name :
  = @user.first_name
%br
%p
  Last Name :
  = @user.last_name
%br
%ul{:class => "user_type"}
  User Type :
  - @user.roles.each do |role|
    %li
      = role.role_name
      - if role != @user.roles.last
        |
%br
%p
  Total Work Time :
  = @user.user_total_work_time
%br
- if @user.has_role?("report manager")
  %h3
    = link_to "Produce Report", report_path
- if @user.has_role?("administrator")
  %h3
    = link_to "View Users", users_path
  %h3
    = link_to "View Projects", administrators_index_project_path
  %h3
    = link_to "View Tasks", administrators_index_task_path
  %h3
    = link_to "Update Personal Information", administrators_edit_user_path(id: @user.id)
- else
  %h3
    = link_to "View Projects", projects_path
  %h3
    = link_to "View Tasks",  index_task_user_path(@user)
  %h3
    = link_to "Update Personal Information", edit_user_path(@user.id)
%h3
  = link_to "Log out", logout_path, method: :delete

app/views/users/reset_password.html.erb
<h1>Reset Password</h1>
<%= form_for @user  do |f| %>
    <%= render partial: 'error_messages', object: @user, as: :item %>
    <%= f.label :password %>
    <%= f.password_field :password%>
    <br/><br/><%= f.label :password_confirmation%>
    <%= f.password_field :password_confirmation %>
    <br/><br/>
    <%= f.submit%>
<% end %>

app/views/users/search_report.html.erb
<% stylesheet_link_tag 'users.scss' %>

<h1>Reports</h1>
<div class="search_wrap">
<%= form_tag report_path do  %>
    <div id="start_time">
      From
      <%= date_field_tag :start_time %>
    </div>
    <div id="end_time">
      To
      <%= date_field_tag :end_time %>
    </div>

    <div id="task">
      Task
      <%= check_box_tag :task_checked %>
    </div>

      <div id="user">
        User
        <%= check_box_tag :user_checked %>
      </div>

      <div id="task_states">
        Task Status
        <%= select_tag :status_selected, options_for_select([["Open", 1], ["In Progress", 2], ["Waiting", 3], ["Resloved", 4]]), prompt: "Please choose a task status" %>
      </div>

      <div id="user_status">
        User Status
        <%= select_tag :user_status_selected, options_for_select([["active", true], ["inactive", false]]), prompt: "Please choose a user status" %>
      </div>
    <div id="submit">
        <%= submit_tag 'search' %>
    </div>

<% end %>
</div>

<div class="report_wrap">
  <ul id="task_list">
    <% if @tasks.present? %>
        <h2>Search Result (<%= @tasks.size %>)</h2>
        <p>Task ID | Task Title | Task Total Work Time</p>
        <b/>
        <% @tasks.each do |t| %>
            <li>
              <%= t.id %> | <%= t.title %> | <%= t.user.user_name %> | <%= t.total_work_time %>
            </li>
        <% end %>
    <% end %>
  </ul>

  <ul id="user_list">
    <% if @users.present? %>
        <h2>Search Result (<%= @users.size %>)</h2>
        <p>User ID | User Name | User Email | Task Total Work Time (h)</p>
        <br/>
        <% @users.each do |t| %>
            <li>
              <%= t.id %> | <%= t.user_name %> | <%= t.email %> | <%= t.total_work_time %>
            </li>
        <% end %>
    <% end %>
  </ul>

  <% if !@tasks.present? && !@users.present? %>
    <h2> Search Result (0) </h2>
  <% end %>

</div>
<br/>

<div class="generate_report">
    <% if @users.present? %>
      <h3><%= link_to "Export Report", report_path(format: :csv, users: @users.each {|t| t.id}) %></h3>

    <% elsif @tasks.present? %>
      <h3><%= link_to "Export Report", report_path(format: :csv, tasks: @tasks.each{|t| t.id}) %></h3>

    <% end %>
</div>