config/routes.rb
Rails.application.routes.draw do

  root to: 'users#profile'
  resources :users, except: [:index, :show, :destroy] do
    member do
      get 'reset_password'
    end
  end

  get '/users', to: 'administrators#index_user'
  get '/users/:id', to: 'administrators#show_user'
  delete '/users/:id', to: 'administrators#destroy_user'
  get '/users/:id/index_task', to: 'tasks#index_task', as: 'index_task_user'
  get '/users/:user_id/tasks/:id/accept_task', to: 'tasks#accept_task', as: 'accept_task_user'

  get 'user/profile', to: 'users#profile'
  namespace :administrators do
    get 'new_user'
    post 'create_user'
    get 'edit_user'
    patch 'update_user'
    put 'update_user'
    get 'index_project'
    get 'index_task'
  end

  resources :projects do
    member  do
      get 'invite_participant'
    end
    resources :tasks do
      member  do
        get 'assign_task'
      end
      member do
        get 'new_subtask'
      end
      member do
        post 'create_subtask'
      end
      resources :hours
      resources :comments, except:[:show]
    end
  end
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get     '/report', to: 'reports#generate'
  post     '/report', to: 'reports#search'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :delete_all
  belongs_to :user
  has_and_belongs_to_many :participants, class_name: "User", join_table: "assigned_projects_participants"
  validates :title, :description, :presence => true
  scope :validated_projects, ->{where(deleted: false)}


  def add_participant(user)
    participants << user
  end

  def update_participant(participants_id)
    # parameter participants indicate an array of participants ids string
    if participants_id.blank?
      # remove user from assigned task
      participants.each do |p|
        remove_task_assignee(p)
      end
      return participants.delete(participants.all)
    end
    participants.each do |p|
      if participants_id.exclude?(p.id.to_s)
        # remove user from assigned task
        remove_task_assignee(p)
        participants.delete(p)
      end
    end
    #add new participant to project
    participants_id.each do |p|
      if !participants.exists?(id: p)
        user = User.find_by(id: p)
        add_participant(user)
      end
    end
  end

  def remove_task_assignee(user)
    tasks.each do |t|
      t.assignees.delete(user)
      t.update_assignment_status
    end
  end

  def set_tasks_to_deleted
    self.tasks.each do |task|
      task.update(deleted: true)
      task.set_subtasks_comments_hours_to_deleted
    end
  end



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :load_project_before_action, only: [:show, :edit, :update, :destroy, :invite_participant]


  def index
    @projects = current_user.assigned_projects.validated_projects
    if params[:project_filter_selected] == "all_projects"
      @projects = current_user.assigned_projects.validated_projects
    elsif params[:project_filter_selected] == "assigned_projects"
      @projects = current_user.assigned_projects.validated_projects
    elsif params[:project_filter_selected] == "create_projects"
      # only show the projects which are created and participated by the user
      @projects = current_user.create_projects_and_participate
    elsif params.has_key?("project_filter_selected") && params[:project_filter_selected].blank?
      flash.notice = "please choose a scope"
      return redirect_to projects_path
    end
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      @project.update_participant(params[:project][:participants_id])
      @project.add_participant(current_user)
      redirect_to @project
    else
      render 'new'
    end
  end

  # set deleted attribute to true when user delete a project
  def destroy
    set_record_to_deleted(@project)
    @project.set_tasks_to_deleted
    redirect_to projects_path
  end

  def edit
  end

  def update
    if @project.update(project_params)
      @project.update_participant(params[:project][:participants_id])
      redirect_to @project
    else
      render 'edit'
    end
  end

  def invite_participant
    if params.has_key?("commit")
      if params.has_key?("project")
        # invite user if choose any users
        @project.update_participant(params[:project][:participants_id])
      else
        # remove all participants if no user is chosen
        @project.update_participant([])
      end
      return redirect_to @project
    end
  end

  private
  def load_project_before_action
    @project = Project.find_by(id: params[:id])
    if @project.blank? || @project.deleted
      flash.notice = "Project doesn't exist !"
      return redirect_to root_path
    end
    # only participants and administrator access a project
    if !current_user.has_role?("administrator") && !@project.participants.exists?(current_user)
      flash.notice = "You don't have privilege !"
      return redirect_to root_path
    end
  end

  def project_params
    params.require(:project).permit(:title, :description)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper



end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
    <%= render partial: 'users/error_messages', object: @project, as: :item %>
    <p>
      <%= f.label :title %><br/>
      <%= f.text_field :title %>
    </p>
    </br>
    <p>
      <%= f.label :description %><br/>
      <%= f.text_area :description %>
    </p>
    </br>
    <p>
      <%= f.label :invite_participants %></br>
      <% if local_assigns[:edit] %>
          <%= f.collection_check_boxes :participants_id, User.where("activated = ?", true), :id, :user_name, :checked => @project.participants.map(&:id), :include_hidden => false %>
      <% else %>
          <%= f.collection_check_boxes :participants_id, User.where("activated = ? and id != ?", true, current_user.id), :id, :user_name, :checked => @project.participants.map(&:id), :include_hidden => false %>
      <% end %>
    </p>
    </br>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/projects/edit.html.erb
<div class="edit-project">
  <h1>Edit a Project</h1>
  <%= render partial: "form", object: @project,  locals: {edit: true} %>
</div>

app/views/projects/index.html.erb
<h1>Projects</h1>

<div class="project-filter">
  <%= form_tag projects_path, :method => :get do  %>
      <div class="project-filter_select">
        Project Filter
        <%= select_tag :project_filter_selected, options_for_select([["All Projects", "all_projects"],["Create Projects", "create_projects"], ["Assigned Projects", "assigned_projects"]]), prompt: "Please choose" %>
      </div>
      <div class="project-filter_submit">
        <%= submit_tag 'submit' %>
      </div>
  <% end %>
</div>

<div class="projects_wrap">
  <h2>Projects (<%= @projects.size %>)</h2>
  <% if @projects.present? %>
      <ul id="projects">
        <% @projects.each do |project| %>
            <li><%= link_to project.title, project, class: 'project_title' %></li>
            <br/>
        <% end %>
      </ul>
  <% end %>
</div>


<%= link_to "Create a New Project", new_project_path, class: "new" %>
<br/><br/>
<h3><%= link_to "<< Back to Personal Profile", root_path %></h3>

app/views/projects/invite_participant.html.haml
.invite_participant
  %h1 Invite Participant
  = form_for @project, url: invite_participant_project_path(@project), method: :get do |f|
    %p
      = f.label :invite_participants
      %br
      = f.collection_check_boxes :participants_id, User.where("activated = ?", true), :id, :user_name, :checked => @project.participants.map(&:id), :include_hidden => false
    %p
      = f.submit "OK"

app/views/projects/new.html.erb
<div class = "new-project">
  <h1>Create a New Project</h1>
  <%= render partial: "form", object: @project,  locals: {edit: false} %>
</div>

app/views/projects/new.js.erb
$('.project-form').html("<%= j (render partial: 'form') %>");
$('.project-form').slideDown(350);

app/views/projects/show.html.erb
<div class="project-wrap">
  <h1><%= @project.title %></h1>
  <p class="project-wrap_author">Author : <%= @project.user.user_name %></p>
  <div class="project-wrap_modify">
    <%= link_to  "invite participant", invite_participant_project_path(@project), {:style=>'color:red'}%>
    | <%= link_to  "edit" , edit_project_path(@project), {:style=>'color:red'} %>
    | <%= link_to  "delete" , @project, :style=>'color:red', method: :delete, data: {confirm: "Really delete the project?"} %>
  </div>
  <br/><br/>
  <p>Created at : <%= @project.created_at %></p>
  <br/>
  <p>Description : <%= @project.description%></p>
  <br/>
  <% if @project.participants.blank? %>
    <p>Participants : No participants</p>
  <% else %>
      <ul class="project-wrap_participant_name"> Participants :
        <% @project.participants.each do |participant| %>
            <li>
              <%= participant.user_name %>
              <% if participant != @project.participants.last %>
                  |
              <% end %>
            </li>
        <% end %>
      </ul>
  <% end %>
</div>
<br/>

<div class="task-wrap">
  <h2>Tasks (<%= @project.tasks.validated_tasks.where(parent_task: nil).count %>)</h2>
  <ul class="task-wrap_task-list">
    <% @project.tasks.validated_tasks.each do |task| %>
        <%# only display parent task %>
        <% if task.parent_task_id == nil %>
            <li>
              <%= link_to task.title, project_task_path(task.project_id, task.id)%>
            </li>
        <%end%>
    <% end %>
  </ul>
</div>
<br/>



<%= link_to "Create Task", new_project_task_path(@project), class: "new" %>
<br/><br/>
<h3>
  <% if current_user.has_role?("administrator") %>
      <%= link_to "<< Back to Project List",administrators_index_project_path %>
  <% else %>
      <%= link_to "<< Back to Project List", projects_path %>
  <% end %>
</h3>