config/routes.rb
Rails.application.routes.draw do

  root to: 'users#profile'
  resources :users, except: [:index, :show, :destroy] do
    member do
      get 'reset_password'
    end
  end

  get '/users', to: 'administrators#index_user'
  get '/users/:id', to: 'administrators#show_user'
  delete '/users/:id', to: 'administrators#destroy_user'
  get '/users/:id/index_task', to: 'tasks#index_task', as: 'index_task_user'
  get '/users/:user_id/tasks/:id/accept_task', to: 'tasks#accept_task', as: 'accept_task_user'

  get 'user/profile', to: 'users#profile'
  namespace :administrators do
    get 'new_user'
    post 'create_user'
    get 'edit_user'
    patch 'update_user'
    put 'update_user'
    get 'index_project'
    get 'index_task'
  end

  resources :projects do
    member  do
      get 'invite_participant'
    end
    resources :tasks do
      member  do
        get 'assign_task'
      end
      member do
        get 'new_subtask'
      end
      member do
        post 'create_subtask'
      end
      resources :hours
      resources :comments, except:[:show]
    end
  end
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get     '/report', to: 'reports#generate'
  post     '/report', to: 'reports#search'
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :is_admin_before_action
  before_action :load_user_before_action, only: [:show_user, :edit_user, :update_user, :destroy_user]

  def index_user
    @users = User.all
    @user = User.find(current_user.id)
  end

  def show_user
  end

  def new_user
    @user = User.new
  end

  def create_user
    @user = User.create(user_params)
    if @user.save
      # assign roles for a new user
      @user.update_role(params[:user][:roles])
      return redirect_to @user
    else
      return render 'new_user'
    end
  end

  def edit_user
  end

  def update_user
    # check if user reset password, if doesn't, skip the password validation
    if params[:user][:password].blank?
      @user.password_validation = false
    end
    if @user.update(user_params)
      # update roles for users
      @user.update_role(params[:user][:roles])
      return redirect_to @user
    else
      return render 'edit_user'
    end
  end

  def destroy_user
    # skip password validation
    @user.password_validation = false
    @user.update(activated: false)
    redirect_to @user
  end

  def index_project
    @projects = Project.all.validated_projects
    if params[:project_filter_selected] == "all_projects"
      @projects = Project.all.validated_projects
    elsif params[:project_filter_selected] == "assigned_projects"
      @projects = current_user.assigned_projects.validated_projects
    elsif params[:project_filter_selected] == "create_projects"
      @projects = current_user.projects.validated_projects
    elsif params.has_key?("project_filter_selected") && params[:project_filter_selected].blank?
      flash.notice = "please choose a scope"
      return redirect_to administrators_index_project_path
    end
  end

  def index_task
    # return the tasks by its relevant: confirmed > pending > create > others
    @tasks = current_user.return_admin_tasks_by_relevant
    if params[:task_filter_selected] == "all_tasks"
      @tasks = current_user.return_admin_tasks_by_relevant
    elsif params[:task_filter_selected] == "confirmed_tasks"
      @tasks = current_user.assigned_and_confirmed_tasks
    elsif params[:task_filter_selected] == "create_tasks"
      @tasks = current_user.tasks.validated_tasks
    elsif params[:task_filter_selected] == "pending_tasks"
      @tasks = current_user.assigned_and_pending_tasks
    elsif params[:task_filter_selected] == "feature"
      @tasks = current_user.return_taks_of_type(current_user.return_admin_tasks_by_relevant, "Feature")
    elsif params[:task_filter_selected] == "bug"
      @tasks = current_user.return_taks_of_type(current_user.return_admin_tasks_by_relevant, "Bug")
    elsif params[:task_filter_selected] == "improvement"
      @tasks = current_user.return_taks_of_type(current_user.return_admin_tasks_by_relevant, "Improvement")
    elsif params.has_key?("task_filter_selected") && params[:task_filter_selected].blank?
      flash.notice = "please choose a scope"
      return redirect_to administrators_index_task_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :email, :first_name, :last_name, :password, :password_confirmation, :activated)
  end

  def load_user_before_action
    @user = User.find_by(id: params[:id])
    if @user.blank?
      flash.notice = "User doesn't exist !"
      redirect_to root_path
    end
  end

end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= form_for @user, url: local_assigns[:submit_path]  do |f| %>
    <%= render partial: 'users/error_messages', object: @user, as: :item %>
    <%= f.label :user_name %>
    <%= f.text_field :user_name%>
    <br/><br/>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br/><br/>
    <%= f.label :first_name%>
    <%= f.text_field :first_name %>
    <br/><br/>
    <%= f.label :last_name%>
    <%= f.text_field :last_name %>
    <br/><br/>
    <% if local_assigns[:sign_up] %>
        <%= f.label :password %>
        <%= f.password_field :password, placeholder: "minimum 4 characters" %>
        <br/><br/>
        <%= f.label :password_confirmation%>
        <%= f.password_field :password_confirmation %>
        <br/><br/>
    <% end %>
    <%= f.label :activate%><br/>
    <%= f.select :activated, options_for_select([["Yes", true], ["No", false]], @user.activated) %>
    <br/><br/>
    <%= f.label :assign_roles %>
    <%= f.collection_check_boxes :roles, Role.all, :id, :role_name, :checked => @user.roles.map{|t| t.id}, :include_hidden => false %>
    <br/><br/>
    <% if local_assigns[:edit] %>
        <%= link_to "Reset Password", reset_password_user_path(@user)%>
        <br/><br/>
    <% end %>
    <%= f.submit%>
<% end %>

app/views/administrators/edit_user.html.erb
<h1>Modify a User</h1>
<%= render partial: "form", object: @user, locals: {sign_up: false, edit: true, submit_path: administrators_update_user_path(id: params[:id])} %>

app/views/administrators/index.html.erb
<h1>All Users</h1>
<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.user_name, user, class: 'user_title' %>
      <% unless user.has_role?("administrator") %>
          | <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" } %>
          | <%= link_to "modify",  administrators_edit_path(id: user.id) %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a New User", administrators_new_path, class: "new" %>
<br/><br/>
<h3><%= link_to "<< Back to Personal Profile", root_path %></h3>

app/views/administrators/index_project.html.haml
%h1 Projects
.admin_project_filter
  = form_tag administrators_index_project_path, :method => :get
  .admin_project_filter_select
    Project Filter
    = select_tag :project_filter_selected, options_for_select([["All Projects", "all_projects"],["Create Projects", "create_projects"], ["Assigned Projects", "assigned_projects"]]), prompt: "Please choose"
  .admin_project_filter_submit
    = submit_tag 'submit'
.admin_projects_wrap
  %h2
    Projects (#{@projects.size})
  - if @projects.present?
    %ul{:id => "admin_projects"}
      - @projects.each do |project|
        %li
          = link_to project.title, project, class: 'project_title'
        %br
= link_to "Create a New Project", new_project_path, remote:true, class: "new"
%br
%br
.project-form{style: "display: none;"}
%h3
  = link_to "<< Back to Personal Profile", root_path

app/views/administrators/index_task.html.haml
%h1 Tasks
.admin_task_filter
  = form_tag administrators_index_task_path, :method => :get
  .admin_task_filter_select
    Task Filter
    = select_tag :task_filter_selected, options_for_select([["All Tasks", "all_tasks"],["Create Tasks", "create_tasks"], ["Confirmed Tasks", "confirmed_tasks"],["Pending Tasks", "pending_tasks"],  ["Feature", "feature"], ["Bug", "bug"], ["Improvement", "improvement"]]), prompt: "Please choose"
  .admin_task_filter_submit
    = submit_tag 'submit'
.admin_tasks_wrap
  %h2
    Tasks (#{@tasks.size})
  - if @tasks.present?
    %ul{:id => "admin_tasks"}
      - @tasks.each do |task|
        %li
          = link_to task.title,  project_task_path(task.project, task), class: 'admin_tasks_wrap_task__title'
          - if task.assignees.exists?(current_user) && task.assignment_confirmed_user_id == nil
            %p{:class => "user_tasks_wrap_task_pending"}
              |
              = link_to image_tag("task_pending.jpg", height: '40', width: '80', class: "task_pending_icon"), accept_task_user_path(current_user, task)
              |
              = link_to image_tag("take_task.jpg", height: '40', width: '40'), accept_task_user_path(current_user, task, accept: true), data: {confirm: "Are you sure to take the task"}
          - if task.assignment_confirmed_user_id == current_user.id
            %p{:class => "user_tasks_wrap_task_confirmed"}
              |
              = image_tag("task_confirmed.jpg", height: '50', width: '80', class: "task_confirmed_icon")
        %br
%br
%br
%h3
  = link_to "<< Back to Personal Profile", root_path

app/views/administrators/index_user.html.erb
<h1>All Users</h1>
<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.user_name, user, class: 'user_title' %>
      <% unless user.has_role?("administrator") %>
          | <%= link_to "deactivate", user, method: :delete, data: { confirm: "Are you sure?" } %>
          | <%= link_to "modify",  administrators_edit_user_path(id: user.id) %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a New User", administrators_new_user_path, class: "new" %>
<br/><br/>
<h3><%= link_to "<< Back to Personal Profile", root_path %></h3>

app/views/administrators/new_user.html.erb
<h1>Create a User</h1>
<%= render partial: "form", object: @user, locals: {sign_up: true, edit: false, submit_path: administrators_create_user_path } %>

app/views/administrators/show.html.erb
<h1><%= @user.user_name %></h1>
<p>Email Address : <%= @user.email%></p>
<br/>
<p>First Name : <%= @user.first_name%></p>
<br/>
<p>Last Name : <%= @user.last_name%></p>
<br/>
<ul class="user_type"> User Type :
  <% @user.roles.each do |role| %>
      <li>
        <%= role.role_name %>
        <% if role != @user.roles.last %>
            |
        <% end %>
      </li>
  <% end %>
</ul>
<br/>
<p>Total Work Time : <%= @user.user_total_work_time %> h</p>
<br/>
<h3><%= link_to "<<Back to User List", users_path %></h3>

app/views/administrators/show_user.html.erb
<h1><%= @user.user_name %></h1>
<p>Email Address : <%= @user.email%></p>
<br/>
<p>First Name : <%= @user.first_name%></p>
<br/>
<p>Last Name : <%= @user.last_name%></p>
<br/>
<ul class="user_type"> User Type :
  <% @user.roles.each do |role| %>
      <li>
        <%= role.role_name %>
        <% if role != @user.roles.last %>
            |
        <% end %>
      </li>
  <% end %>
</ul>
<br/>
<p>Total Work Time : <%= @user.user_total_work_time %> h</p>
<br/>
<h3><%= link_to "<<Back to User List", users_path %></h3>